{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tools.module",
    "module": "module-network",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tools.module",
          "module": "module-common",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okio",
              "module": "okio"
            },
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okio",
              "module": "okio"
            },
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okio",
              "module": "okio"
            },
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "module-network-1.0.9.aar",
          "url": "module-network-1.0.9.aar",
          "size": 40502,
          "sha512": "a7c1d1ffe712b6837c1be065d6da7918a5b0a191f70687eb30e960cb35b9f51d57168f73b72957751590289aea8f1b51304186e42167575df36dfab1bf40b96d",
          "sha256": "ec453a3baef15897e1ff8769e2fe355fe8eb6aa959f02d7aee658870f127a80d",
          "sha1": "36ddb93675efec04559c28c9ac1eaa9b7cfc0e8b",
          "md5": "a578194d9542344aa0962de3bbe4abcb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tools.module",
          "module": "module-common",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okio",
              "module": "okio"
            },
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okio",
              "module": "okio"
            },
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.squareup.okio",
              "module": "okio"
            },
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "module-network-1.0.9.aar",
          "url": "module-network-1.0.9.aar",
          "size": 40502,
          "sha512": "a7c1d1ffe712b6837c1be065d6da7918a5b0a191f70687eb30e960cb35b9f51d57168f73b72957751590289aea8f1b51304186e42167575df36dfab1bf40b96d",
          "sha256": "ec453a3baef15897e1ff8769e2fe355fe8eb6aa959f02d7aee658870f127a80d",
          "sha1": "36ddb93675efec04559c28c9ac1eaa9b7cfc0e8b",
          "md5": "a578194d9542344aa0962de3bbe4abcb"
        }
      ]
    }
  ]
}
