{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tools.module",
    "module": "module-upgrade",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tools.module",
          "module": "module-common",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport",
          "version": {
            "requires": "4.1.9.3"
          }
        },
        {
          "group": "com.tencent.shiply",
          "module": "upgrade",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.tencent.shiply",
          "module": "upgrade-ui",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "module-upgrade-1.1.0.aar",
          "url": "module-upgrade-1.1.0.aar",
          "size": 19445,
          "sha512": "13e84783b63f8fd54e7161ab9e3e7c59af5f4ca0bec83bef34f1b4ede54948ddaaa0faf31f8a4bccf11aa00aa25f2df15de3fa9ce9bed27a363a38c705487b9e",
          "sha256": "b90afefb95170696a9988ec9fcb2fd8395068b9e1a773bca29561b1e2d2d6eda",
          "sha1": "f95782562e7398602d0d307311944e968bda667f",
          "md5": "eddfdccba8680df73bd37e6ee9dcb19a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tools.module",
          "module": "module-common",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport",
          "version": {
            "requires": "4.1.9.3"
          }
        },
        {
          "group": "com.tencent.shiply",
          "module": "upgrade",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.tencent.shiply",
          "module": "upgrade-ui",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "module-upgrade-1.1.0.aar",
          "url": "module-upgrade-1.1.0.aar",
          "size": 19445,
          "sha512": "13e84783b63f8fd54e7161ab9e3e7c59af5f4ca0bec83bef34f1b4ede54948ddaaa0faf31f8a4bccf11aa00aa25f2df15de3fa9ce9bed27a363a38c705487b9e",
          "sha256": "b90afefb95170696a9988ec9fcb2fd8395068b9e1a773bca29561b1e2d2d6eda",
          "sha1": "f95782562e7398602d0d307311944e968bda667f",
          "md5": "eddfdccba8680df73bd37e6ee9dcb19a"
        }
      ]
    }
  ]
}
