{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tools.module",
    "module": "module-shapeview",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tools.module",
          "module": "module-common",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "module-shapeview-1.0.0.aar",
          "url": "module-shapeview-1.0.0.aar",
          "size": 189761,
          "sha512": "3fa74362bfcf400234c3b43ecec346ce2a934742fc4ef3c618ce208783f6f3ed8a5d9dcbded7c54698d58865e7084c91814944103f29b5dcc2d4f546cf6ded02",
          "sha256": "08d232f84b2b379ddc5608498be535f09caad076836cdd50ad0e432ad28e2a65",
          "sha1": "f78836a32a2f3a9be82cbd5dfa67b70b77ee2189",
          "md5": "312b5d039d216ebb41f452103f0a1ad8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.tools.module",
          "module": "module-common",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "module-shapeview-1.0.0.aar",
          "url": "module-shapeview-1.0.0.aar",
          "size": 189761,
          "sha512": "3fa74362bfcf400234c3b43ecec346ce2a934742fc4ef3c618ce208783f6f3ed8a5d9dcbded7c54698d58865e7084c91814944103f29b5dcc2d4f546cf6ded02",
          "sha256": "08d232f84b2b379ddc5608498be535f09caad076836cdd50ad0e432ad28e2a65",
          "sha1": "f78836a32a2f3a9be82cbd5dfa67b70b77ee2189",
          "md5": "312b5d039d216ebb41f452103f0a1ad8"
        }
      ]
    }
  ]
}
